include: ['_pages']

# Site settings
title: Sublime Next
description: "notepad"

# Build settings
markdown: kramdown

permalink: /:slug

collections:
  tag:
    output: true
    permalink: /tag/:name/
